=== juancaballero5/Lenguaje-de-Marcas/Unidad 01/banco.dtd
<!ELEMENT banco (sucursal+)>
<!ELEMENT sucursal (cuenta+)>
<!ATTLIST sucursal ID NMTOKEN #IMPLIED>
<!ATTLIST sucursal id NMTOKEN #IMPLIED>
<!ELEMENT cuenta (cliente+,saldo?,codigo?)>
<!ATTLIST cuenta iban NMTOKEN #IMPLIED>
<!ELEMENT cliente (nombre?,numero?,telefono?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT saldo EMPTY>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT codigo EMPTY>

=== juancaballero5/Lenguaje-de-Marcas/Unidad 01/banco.xml
<!DOCTYPE banco SYSTEM "banco.dtd">
<banco>
    <!--Sucursal 1-->
    <sucursal ID="S001">
        <cuenta iban="C001S1">
            <cliente>
                <nombre>Antonio Gomez</nombre>
                <numero>123456789</numero>
            </cliente>
            <cliente>
                <nombre>Jose Montero</nombre>
                <numero>123123123</numero>
            </cliente>
            <saldo></saldo>
        </cuenta>
        <!--Cuenta 2 de la sucursal 1-->
        <cuenta iban="C002S1">
            <cliente>
                <nombre></nombre>
                <telefono></telefono>
            </cliente>
        </cuenta>
    </sucursal>

    <!--Sucursal 2-->
    <sucursal id="S002">
        <cuenta iban="C002S1">
            <cliente>
                <nombre>Mario Torrente</nombre>
                <telefono>456234456</telefono>
            </cliente>
        </cuenta>
    </sucursal>
</banco>
