=== juancaballero5/Lenguaje-de-Marcas/Unidad 01/ExamenPepito/T1-Exam-Correccion-CaballeroJuan.dtd
<!ELEMENT catalogo (libro+,resumen)>
<!ELEMENT libro (titulo,autor,detalles)>
<!ATTLIST libro id NMTOKEN #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT detalles (editorial,precio,stock?)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>

=== juancaballero5/Lenguaje-de-Marcas/Unidad 01/ExamenPepito/T1-Exam-Correccion-CaballeroJuan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "T1-Exam-Correccion-CaballeroJuan.dtd"> 
<catalogo>
  <libro id="1">
    <titulo>La metamorfosis</titulo>
    <autor>Kafka</autor>
    <detalles>
      <editorial>ID Ediciones</editorial>
      <precio>9.95</precio>
      <stock>5</stock>
    </detalles>
  </libro>
  <libro id="2">
    <titulo>Rayuela</titulo>
    <autor>Cort√°zar</autor>
    <detalles>
      <editorial>Alfaguara</editorial>
      <precio>19.95</precio>
    </detalles>
  </libro>
  <resumen>TOTAL: 2 libros</resumen>
</catalogo>
